<<<<<<< HEAD
OPENAI_API_KEY: "NA"
SERPER_API_KEY: "YOUR_API_KEY"
OPENAI_API_BASE: "http://localhost:11434/api/generate"
=======
OPENAI_API_KEY: "YOUR API KEY"
SERPER_API_KEY: "YOUR API KEY"
>>>>>>> main
